# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
variables:
  - name: one
    value: V1

steps:
  - script: echo $(one)
    displayName: 'Macro'

  - script: echo ${{variables.one}} 
    displayName: 'Expression'

  - script: echo '##vso[task.setvariable variables=one]V2'
    displayName: 'Changement de valeur de V1 à V2'
    
  - script: echo $(one)
    displayName: 'Macro'

  - script: echo ${{variables.one}} 
    displayName: 'Expression'