# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
variables:
  global_variable1: GV1

stages:
    - stage: 'Build'
      variables:
        stage_variable1: SV1
      jobs:
        - job: 'BuildJob1'
          variables: 
            job_variable1: JV1
          steps:
          - script: echo $(global_variable1)
          - script: echo $(stage_variable1)
          - script: echo $(job_variable1)
            displayName: 'Execution dans le premier stage'

        - job: 'BuildJob2'
          steps:
            - script: echo $(global_variable1)
            - script: echo $(stage_variable1)
            - script: echo $(job_variable1)
